/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  mode: 'jit',
  theme: {
    extend: {
      colors: {
        'background-dark': '#0A0C10',
        'card-dark': '#141924',
        'input-dark': '#1E2330',
        'foreground-dark': '#F8F9FA',
        'muted-foreground': '#9CA3AF',
        'accent': '#B0E681',
        'accent-hover': '#9ED065',
        'border-dark': '#2A3041',
        'destructive': '#FF5555',
        'neon-green': '#B0E681',
        'neon-green-100': '#C8EDA5',
        'neon-blue': '#5078FF',
        'neon-blue-100': '#A6C8FF',
        'neon-red': '#FF5555',
        'neon-red-100': '#FFB3B3',
        'neon-yellow': '#FFB86C',
        'neon-yellow-100': '#FFE0B3',
        'neon-purple': '#BD93F9',
        'neon-purple-100': '#D9C6FD',
        primary: {
          DEFAULT: 'var(--primary)',
          dark: 'var(--primary-dark)',
          light: 'var(--primary-light)',
        },
        secondary: {
          DEFAULT: '#6b7280',
          dark: '#4b5563',
          light: '#9ca3af',
        },
        success: {
          DEFAULT: 'var(--success-text)',
          bg: 'var(--success-bg)',
        },
        warning: {
          DEFAULT: 'var(--warning-text)',
          bg: 'var(--warning-bg)',
        },
        error: {
          DEFAULT: 'var(--error-text)',
          bg: 'var(--error-bg)',
        },
        info: {
          DEFAULT: 'var(--info-text)',
          bg: 'var(--info-bg)',
        },
      },
      backgroundImage: {
        'gradient-accent': 'linear-gradient(to right, #B0E681, #84cc16)',
      },
      fontFamily: {
        sans: ['var(--font-family)', 'sans-serif'],
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        DEFAULT: 'var(--shadow)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        enhanced: 'var(--shadow-enhanced)',
      },
      borderRadius: {
        DEFAULT: 'var(--radius)',
      },
      transitionProperty: {
        all: 'var(--transition-all)',
      },
      animation: {
        'slide-in': 'slideIn 0.3s ease-out forwards',
        'fade-out': 'fadeOut 0.3s ease-out forwards',
      },
      keyframes: {
        slideIn: {
          '0%': { transform: 'translateX(100%)', opacity: 0 },
          '100%': { transform: 'translateX(0)', opacity: 1 },
        },
        fadeOut: {
          '0%': { opacity: 1 },
          '100%': { opacity: 0 },
        },
      },
    },
  },
  plugins: [],
  safelist: [
    'bg-blue-500',
    'text-white',
    'bg-gray-500',
    'bg-green-500',
    'hover:bg-blue-600',
    'hover:bg-gray-600',
    'hover:bg-green-600',
    'px-3',
    'py-1',
    'px-4',
    'py-2',
    'px-6',
    'py-3',
    'text-sm',
    'text-base',
    'text-lg',
    'w-full',
    'opacity-50',
    'cursor-not-allowed',
    'cursor-pointer',
    'bg-primary',
    'bg-primary-dark',
    'bg-primary-light',
    'text-primary',
    'text-primary-dark',
    'text-primary-light',
    'border-primary',
    'shadow-sm',
    'shadow-md',
    'shadow-lg',
    'shadow-enhanced',
  ],
} 